# Generated by Django 4.0 on 2023-03-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0019_alter_order_status_orderitem'),
        ('app_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_item',
            field=models.ManyToManyField(related_name='invoices', to='app_order.OrderItem', verbose_name='плаченный товар'),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
