#version: '3.9'
#
#services:
#
#  # Database Postgres
#  db:
#    container_name: postgres_container
#    image:  postgres:14.6-alpine
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgresUSER
#      - POSTGRES_PASSWORD=postgresPASS
#    volumes:
#       - postgres_volume:/var/lib/postgresql/data/
##      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
#    ports:
#       - "5432:5432"
#
#  # Django Application
#  app:
#    build:
#        dockerfile: Dockerfile
#        context: ./shop
#    container_name: app_shop
#    command: >
#      sh -c "python manage.py runserver 0.0.0.0:8000"
#    depends_on:
#      - db
#    volumes:
#      - ./shop/:/usr/src/app/
#    ports:
#      - 8000:8000
#    env_file:
#      - ./.env
#
#volumes:
#  postgres_volume:
#
#
#  # Database Postgres
##  db:
##    image: postgres
##    restart: always
##    volumes:
##      - ./db-data/:/var/lib/postgresql/data/
##    environment:
##      - POSTGRES_DB=postgres
##      - POSTGRES_NAME=postgres
##      - POSTGRES_USER=postgres
##      - POSTGRES_PASSWORD=postgres
##      - POSTGRES_HOST=db
##    ports:
##      - "5432:5432"
#
##    container_name: db
#
#
##  adminer:
##    image: adminer
##    restart: always
##    ports:
##      - 8080:8080
#
#  # Redis
##  redis:
##    image: redis:7.0.5-alpine
##    container_name: redis
##
##  # Celery
##  celery:
##    restart: always
##    build:
##      context: ./shop
##    hostname: worker
##    command:  celery --app=shop worker --loglevel=info --logfile=logs/celery.log
##    volumes:
##      - ./shop:/usr/scr/app
##    environment:
##      - POSTGRES_DB=postgres
##      - POSTGRES_USER=postgres
##      - POSTGRES_PASSWORD=postgres
##      - POSTGRES_HOST=db
##    links:
##      - redis
##    container_name: celery
##    depends_on:
##      - postgres
##      - redis
##
