version: '3.7'

services:
  database:
    image: postgres:14.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/

    env_file:
       - /.env
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgresUSER
#      - POSTGRES_PASSWORD=postgresPASS

  shop_app:
    container_name: shop_app
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn shop.wsgi:application --bind 0.0.0.0:8000
    expose:
        - 8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
#      - ./shop:/usr/src/app
    ports:
      - 8000:8000
    env_file:
         - /.env
#
    depends_on:
             - database
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - shop_app
volumes:
  pg_data:
  static_volume:
  media_volume:
