# Generated by Django 4.0 on 2023-01-15 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
        ('app_item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='app_item.category', verbose_name='родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), (' magenta', 'magenta'), ('white', 'white'), ('black', 'black'), ('grey', 'grey')], max_length=10, null=True, verbose_name='цвет товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ManyToManyField(related_name='item_images', to='app_item.Image', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_store.store', verbose_name='магазин'),
        ),
    ]
