# Generated by Django 4.0 on 2023-05-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='static/img/default_flat.jpg', height_field='800', null=True, upload_to='gallery/%Y/%m/%d', verbose_name='изображение', width_field='600'),
        ),
    ]
