# Generated by Django 4.0 on 2023-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0002_remove_image_main_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='характеристика')),
                ('slug', models.SlugField(max_length=100)),
                ('value', models.CharField(max_length=200, verbose_name='значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='активная характеристика')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
                'db_table': 'app_features',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='features',
            field=models.ManyToManyField(blank=True, max_length=20, related_name='item_features', to='app_item.Feature', verbose_name='характеристики'),
        ),
    ]
