# Generated by Django 4.0 on 2023-01-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0004_featurevalue_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app_item.category', verbose_name='категория'),
        ),
    ]
