# Generated by Django 4.0 on 2023-01-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0005_feature_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='feature',
            field=models.ManyToManyField(blank=True, max_length=200, related_name='categories', to='app_item.Feature', verbose_name='характеристика'),
        ),
    ]
