# Generated by Django 4.0 on 2023-05-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0005_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='assets/img/default/default_item.png', null=True, upload_to='gallery/%Y/%m/%d', verbose_name='изображение'),
        ),
    ]
