# Generated by Django 4.0 on 2023-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0006_rename_image_item_images_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='архивный товар'),
        ),
    ]
