# Generated by Django 4.0 on 2023-02-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_item', '0006_remove_feature_category_category_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='', verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='auth.user', verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='widget_type',
            field=models.CharField(blank=True, choices=[('CBX', 'checkbox'), ('SLC', 'select'), ('TXT', 'textfield')], default='CBX', max_length=3, null=True, verbose_name='тип виджета'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), (' magenta', 'magenta'), ('white', 'white'), ('black', 'black'), ('brown', 'brown')], max_length=10, null=True, verbose_name='цвет товара'),
        ),
    ]
