# Generated by Django 4.0 on 2023-02-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_item', '0007_ipaddress_created_ipaddress_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_address', to='auth.user', verbose_name='пользователь'),
        ),
    ]
