# Generated by Django 4.0 on 2023-06-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0007_item_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('magenta', 'magenta'), ('white', 'white'), ('black', 'black'), ('brown', 'brown')], max_length=10, null=True, verbose_name='цвет товара'),
        ),
    ]
