# Generated by Django 4.0 on 2023-03-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0008_alter_ipaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='удален в архив'),
        ),
    ]
