# Generated by Django 4.0 on 2023-06-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0008_alter_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='в архиве'),
        ),
    ]
