# Generated by Django 4.0 on 2023-03-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0009_comment_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
