# Generated by Django 4.0 on 2023-06-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0009_category_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurevalue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активное значение'),
        ),
    ]
