# Generated by Django 4.0 on 2022-11-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена товара')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('is_paid', models.BooleanField(default=False, verbose_name='статус оплаты')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='app_item.item')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_is_paid', to='app_order.order', verbose_name='заказ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_add_items', to='auth.user', verbose_name='покупатель')),
            ],
            options={
                'verbose_name': 'выбранный товар',
                'db_table': 'app_items_in_cart',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='корзина анонимного пользователя')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='ключ сессии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('items', models.ManyToManyField(related_name='all_items', to='app_cart.CartItem', verbose_name='товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='auth.user', verbose_name='покупатель')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
                'db_table': 'app_carts',
                'ordering': ['created'],
            },
        ),
    ]
