# Generated by Django 4.0 on 2022-11-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0004_alter_cartitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='корзина оплачена'),
        ),
    ]
