# Generated by Django 4.0 on 2022-12-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0005_cart_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_paid',
            new_name='is_archived',
        ),
    ]
