# Generated by Django 4.0 on 2022-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0006_rename_is_paid_cart_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='корзина в архиве'),
        ),
    ]
