# Generated by Django 4.0 on 2023-03-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0010_cartitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('in_cart', 'в корзине'), ('not_paid', 'заказан'), ('in_progress', 'собирается'), ('on_the_way', 'доставляется'), ('is_ready', 'готов к выдаче'), ('completed', 'доставлен'), ('deactivated', 'отменен')], default='in_cart', max_length=20, verbose_name='статус выбранного товара'),
        ),
    ]
