# Generated by Django 4.0 on 2023-03-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0012_remove_cartitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='status',
        ),
    ]
