# Generated by Django 4.0 on 2023-04-09 11:22

import app_user.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        ('app_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADM', 'администратор'), ('SLR', 'продавец'), ('CSR', 'покупатель')], default='CSR', max_length=3, verbose_name='роль')),
                ('avatar', models.ImageField(default='', upload_to=app_user.models.user_dir_path, verbose_name='аватар')),
                ('telephone', models.CharField(max_length=18, unique=True, verbose_name='телефон')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('review_items', models.ManyToManyField(related_name='item_views', to='app_item.Item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
                'ordering': ['user'],
            },
        ),
    ]
