# Generated by Django 4.0 on 2023-06-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_remove_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активный профиль'),
        ),
    ]
