# Generated by Django 4.0 on 2022-11-11 06:47

import app_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_profile_role_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to=app_user.models.profile_directory_path, verbose_name='аватар'),
        ),
    ]
