# Generated by Django 4.0 on 2023-01-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_accountdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountData',
        ),
    ]
