# Generated by Django 4.0 on 2023-03-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_delete_accountdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(max_length=18, unique=True, verbose_name='телефон'),
        ),
    ]
