# Generated by Django 4.0 on 2023-06-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['title', 'created'], 'verbose_name': 'магазин', 'verbose_name_plural': 'магазины'},
        ),
    ]
