# Generated by Django 4.0 on 2023-03-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='delivery_fees',
        ),
        migrations.AddField(
            model_name='store',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='скидка'),
        ),
    ]
