# Generated by Django 4.0 on 2023-03-14 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_remove_store_delivery_fees_store_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='discount',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='store',
            name='min_for_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='минимальная сумма бесплатной доставки'),
        ),
    ]
