# Generated by Django 4.0 on 2022-10-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='имя получателя')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('is_ready', 'Готов'), ('completed', 'Выполнен'), ('deactivated', 'Отменен')], max_length=20, verbose_name='статус заказа')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма заказа')),
                ('delivery', models.CharField(choices=[('express', 'экспресс'), ('standard', 'обычная')], max_length=20, verbose_name='доставка')),
                ('pay', models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счета')], max_length=20, verbose_name='оплата')),
                ('email', models.EmailField(max_length=250, verbose_name='электронная почта')),
                ('telephone', models.CharField(max_length=20, verbose_name='телефон')),
                ('city', models.CharField(max_length=200, verbose_name='город')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='auth.user')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'app_order',
                'ordering': ['created'],
            },
        ),
    ]
