# Generated by Django 4.0 on 2023-04-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0001_initial'),
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'сформирован'), ('paid', 'оплачен'), ('is_preparing', 'собирается'), ('on_the_way', 'доставляется'), ('is_ready', 'готов'), ('completed', 'доставлен'), ('deactivated', 'отменен')], default='created', max_length=20, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='app_cart.cartitem'),
        ),
    ]
