# Generated by Django 4.0 on 2023-04-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_alter_order_status_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='в архив'),
        ),
    ]
