# Generated by Django 4.0 on 2022-12-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_order_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
