# Generated by Django 4.0 on 2022-12-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0005_order_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='номер карты')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app_order.order', verbose_name='чек')),
            ],
            options={
                'verbose_name': 'квитанция',
                'verbose_name_plural': 'квитанции',
                'db_table': 'app_invoices',
                'ordering': ['-created'],
            },
        ),
    ]
