# Generated by Django 4.0 on 2022-12-07 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0007_order_store_alter_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_store_invoices', to='app_store.store', verbose_name='магазин получатель'),
            preserve_default=False,
        ),
    ]
