# Generated by Django 4.0 on 2023-02-06 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_order', '0009_alter_invoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'в обработке'), ('on_the_way', 'доставляется'), ('is_ready', 'готов к выдаче'), ('completed', 'доставлен'), ('deactivated', 'отменен')], max_length=20, verbose_name='статус заказа'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='город')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='auth.user')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адреса',
                'db_table': 'app_post_address',
                'ordering': ['-created'],
            },
        ),
    ]
