# Generated by Django 4.0 on 2023-02-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0010_alter_order_status_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('express', 'экспресс доставка'), ('standard', 'обычная доставка'), ('oneself', 'самовывоз')], max_length=20, verbose_name='доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счета'), ('bonus', 'бонусами')], max_length=20, verbose_name='оплата'),
        ),
    ]
