# Generated by Django 4.0 on 2023-03-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0011_alter_order_delivery_alter_order_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('standard', 'обычная доставка'), ('express', 'экспресс доставка'), ('oneself', 'самовывоз')], max_length=20, verbose_name='доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'сформирован'), ('paid', 'плачен'), ('on_the_way', 'доставляется'), ('is_ready', 'готов к выдаче'), ('completed', 'доставлен'), ('deactivated', 'отменен')], max_length=20, verbose_name='статус заказа'),
        ),
    ]
