# Generated by Django 4.0 on 2023-03-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
        ('app_order', '0012_alter_order_delivery_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ManyToManyField(related_name='orders', to='app_store.Store', verbose_name='магазины'),
        ),
    ]
