# Generated by Django 4.0 on 2023-03-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0014_order_delivery_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='сумма'),
        ),
    ]
