# Generated by Django 4.0 on 2023-03-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
        ('app_order', '0015_invoice_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=20, verbose_name='номер платежного документа'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_store_invoices', to='app_store.store', verbose_name='магазин получатель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'сформирован'), ('paid', 'оплачен'), ('on_the_way', 'доставляется'), ('is_ready', 'готов к выдаче'), ('completed', 'доставлен'), ('deactivated', 'отменен')], max_length=20, verbose_name='статус заказа'),
        ),
    ]
