# Generated by Django 4.0 on 2023-03-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0016_alter_invoice_number_alter_invoice_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'сформирован'), ('paid', 'оплачен'), ('on_the_way', 'доставляется'), ('is_ready', 'готов к выдаче'), ('completed', 'доставлен'), ('deactivated', 'отменен')], default='created', max_length=20, verbose_name='статус заказа'),
        ),
    ]
