# Generated by Django 4.0 on 2023-03-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='сумма заказа'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
