# Generated by Django 4.0 on 2023-03-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0012_remove_cartitem_order'),
        ('app_order', '0018_alter_order_total_sum_delete_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'сформирован'), ('paid', 'оплачен'), ('is_preparing', 'собирается'), ('on_the_way', 'доставляется'), ('is_ready', 'готов к выдаче'), ('completed', 'доставлен'), ('deactivated', 'отменен')], default='created', max_length=20, verbose_name='статус заказа'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена товара')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='app_cart.cartitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app_order.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'оплаченный товар',
                'verbose_name_plural': 'оплаченный товары',
                'db_table': 'app_order_item',
                'ordering': ['-created'],
            },
        ),
    ]
