# Generated by Django 4.0 on 2023-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0020_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('not_paid', 'заказан'), ('paid', 'оплачен'), ('in_progress', 'собирается'), ('on_the_way', 'доставляется'), ('is_ready', 'готов к выдаче'), ('completed', 'доставлен'), ('deactivated', 'отменен')], default='in_cart', max_length=20, verbose_name='статус выбранного товара'),
        ),
    ]
