# Generated by Django 4.0 on 2023-02-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_delivery_price', models.SmallIntegerField(default=500, verbose_name='стоимость экспресс доставки')),
                ('cache_detail_view', models.IntegerField(default=86400, verbose_name='время кэширования страницы товара')),
                ('type_of_delivery', models.CharField(choices=[('express', 'экспресс доставка'), ('standard', 'обычная доставка'), ('oneself', 'самовывоз')], default='standard', max_length=256, verbose_name='тип доставки')),
                ('type_of_payment', models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счета'), ('bonus', 'бонусами')], default='online', max_length=256, verbose_name='тип оплаты')),
                ('url', models.URLField(max_length=256, verbose_name='Website url')),
                ('title', models.CharField(default='Megano', max_length=256, verbose_name='название сайта')),
                ('support_email', models.EmailField(default='Support@ninzio.com', max_length=254)),
                ('phone', models.CharField(default='8-800-200-600', max_length=256, verbose_name='телефон')),
                ('skype', models.CharField(default='techno', max_length=256, verbose_name='телефон')),
                ('address', models.CharField(default='New York, north Avenue 26/7 0057 ', max_length=256, verbose_name='телефон')),
                ('facebook', models.CharField(default='https://facebook.com/megano', max_length=256, verbose_name='телефон')),
                ('twitter', models.CharField(default='https://twitter.com/megano', max_length=256, verbose_name='телефон')),
                ('linkedIn', models.CharField(default='https://linkedin.com/megano', max_length=256, verbose_name='телефон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')),

    ],
            options={
                'verbose_name_plural': 'Настройки',
                'db_table': 'app_site_settings',
            },
        ),
    ]