# Generated by Django 4.0 on 2023-03-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_fees',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=9, verbose_name='стоимость доставки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_free_delivery',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=9, verbose_name='минимальная сумма для бесплатной доставки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='express_delivery_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=9, verbose_name='стоимость экспресс доставки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='type_of_delivery',
            field=models.CharField(choices=[('standard', 'обычная доставка'), ('express', 'экспресс доставка'), ('oneself', 'самовывоз')], default='standard', max_length=256, verbose_name='тип доставки'),
        ),
    ]
