# Generated by Django 4.0 on 2023-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_sitesettings_delivery_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='New York, north Avenue 26/7 0057 ', max_length=256, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_fees',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=9, verbose_name='стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='express_delivery_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9, verbose_name='стоимость экспресс доставки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook',
            field=models.CharField(default='https://facebook.com/megano', max_length=256, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedIn',
            field=models.CharField(default='https://linkedin.com/megano', max_length=256, verbose_name='linkedIn'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='skype',
            field=models.CharField(default='techno', max_length=256, verbose_name='skype'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(default='Support@ninzio.com', max_length=254, verbose_name='электронный ящик'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter',
            field=models.CharField(default='https://twitter.com/megano', max_length=256, verbose_name='twitter'),
        ),
    ]
